default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: accredit_development
  username: postgres
  password:

test:
  <<: *default
  database: accredit_test
  username: postgres
  password:


production:
  <<: *default
  database: accredit_production
  url: <%= ENV['DATABASE_URL'] %>
